### ISSUE TITLE
Fix Hessenberger version of Tikhonov

### ISSUE THREAD

**Issue by raffaello-camoriano** [raffaello-camoriano/Enitor#11]
Fix Hessenberger version of Tikhonov regularization filter.

Currently deactivated, generating a warning.

**Comment by Ommac** [comment]
- <img src="https://latex.codecogs.com/gif.latex?s=\text { sensor reading }  ">

**Comment by Ommac** [comment]
![equation](http://latex.codecogs.com/gif.latex?%5Cint_%7Ba%7D%5E%7Bb%7D%20x%5E2%20dx)
